# fly.toml app configuration file generated for quickviz on 2024-03-19T20:15:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quickviz"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
